/* 组织、账号与角色管理原型：演示数据。 */
(() => {
  const orgs=[['用友网络科技股份有限公司','59228a1276195c00014c05fa','0','集团','启用'],['TEST1','5bc59c3592b225000189a1e0','1','测试组织','启用'],['集团总部','62cd41ed40f22300014a0026','1','总部','启用'],['金融服务','60e66f86b812410001f402dc','1','事业部','启用'],['行业公司','62cd428c40f22300014a0070','1','事业部','启用'],['区域公司','62cd44b9bf24de0001993cb3','1','区域','启用'],['战略本部','62c63320fe0da60001734189','1','总部','停用']];
  const accounts=[['jilin','吉林分公司','186****1612','其他','吉林分公司','wenxt@yonyou.com','正常','2026-06-18'],['jilin-GXFW','佟玲','137****5687','其他','吉林分公司','tongling@yonyou.com','正常','2023-04-26'],['yhhyuntongxin','邢伟','188****3506','近30天登录','云通信','xingwei@yonyou.com','正常','2026-09-20'],['market-admin','陈玉琴','139****0862','今日登录','集团市场部','chenyq@yonyou.com','正常','2026-09-20']];
  const roles=[['超级管理员','超级管理员 · 租户管理员','系统角色','42','全部管理权限'],['运营管理员','默认机构运营角色','系统角色','18','内容、活动、触达与线索'],['yhh superadmin','友户会超管 · 集团市场','自定义角色','6','活动与全员营销'],['yhh branchadmin','友户会分会管理员 · 区域机构运营','自定义角色','24','区域活动与客户'],['活动协作人员','年会专用临时角色','自定义角色','8','活动查看与协作']];
  const toast=message=>{const node=document.getElementById('mkNavNotice');node.textContent=message;node.hidden=false;setTimeout(()=>node.hidden=true,2400);};
  const bindActions=root=>root.querySelectorAll('[data-admin-action]').forEach(button=>button.onclick=()=>toast(`${button.dataset.adminAction}：本原型仅展示入口。`));
  function renderOrganizations(){
    const root=document.getElementById('organizationManagement');
    root.innerHTML=`<div class="sms-header"><div><h3>组织管理</h3><p>维护企业组织层级及其业务配置关系。</p></div><button class="primary-button" data-admin-action="新建组织">＋ 新建组织</button></div><div class="admin-panel"><div class="admin-notice"><b>配置提示</b><span>组织最多支持 5 级；存在子组织或账号时不可删除。调整组织关系前请先确认业务影响。</span></div><div class="organization-table"><b>组织机构</b><b>组织ID</b><b>类型</b><b>操作</b>${orgs.map(row=>`<span class="org-name level-${row[2]}">${row[2]==='0'?'⌄':'›'} <strong>${row[0]}</strong></span><span><code>${row[1]}</code></span><span>${row[3]}</span><span class="admin-actions"><button data-admin-action="编辑组织">编辑</button><button data-admin-action="新增下级">新增下级</button><details><summary>更多</summary><div><button data-admin-action="推送地址">推送地址</button><button data-admin-action="留资设置">留资设置</button><button data-admin-action="公司名片">公司名片</button><button data-admin-action="关联EHR">关联EHR</button><button data-admin-action="删除组织" class="danger">删除</button></div></details></span>`).join('')}</div></div>`;
    bindActions(root);
  }
  function renderAccounts(){
    const root=document.getElementById('accountManagement');
    const accountOrgs=[...new Set(accounts.map(row=>row[4]))];let activeOrg=accountOrgs[0];
    root.innerHTML=`<div class="sms-header"><div><h3>账号管理</h3><p>先选择组织，再查看和新增该组织的管理员账号。</p></div></div><div class="account-layout"><aside><h4>组织</h4>${accountOrgs.map((org,index)=>`<div class="account-org ${index===0?'active':''}"><button data-account-org="${org}">${org}<small>${accounts.filter(row=>row[4]===org).length}</small></button><button class="account-add" data-admin-action="为${org}添加账号">添加账号</button></div>`).join('')}</aside><section class="admin-panel"><div class="admin-toolbar account"><label><span>账号关键字</span><input type="search" placeholder="用户名、姓名、手机或邮箱" data-account-query></label><label><span>账号状态</span><select data-account-status><option>全部状态</option><option>正常</option><option>停用</option></select></label><label><span>登录状态</span><select data-login-status><option>全部登录状态</option><option>今日登录</option><option>近30天登录</option><option>其他</option></select></label><button class="primary-button" data-account-search>查询</button><button class="ghost-button" data-account-reset>重置</button></div><div class="account-table"><b>用户名 / 姓名</b><b>手机号 / 邮箱</b><b>登录状态</b><b>账号状态</b><b>上次登录</b><b>操作</b>${accounts.map(row=>`<span><strong>${row[0]}</strong><small>${row[1]}</small></span><span>${row[2]}<small>${row[5]}</small></span><span>${row[3]}</span><span><em>${row[6]}</em></span><span>${row[7]}</span><span class="admin-actions"><button data-admin-action="编辑账号">编辑</button><details><summary>更多</summary><div><button data-admin-action="修改密码">修改密码</button><button data-admin-action="切换机构">切换机构</button><button data-admin-action="停用账号" class="danger">停用</button></div></details></span>`).join('')}</div></section></div>`;
    const filter=()=>{const query=root.querySelector('[data-account-query]').value.trim().toLowerCase(),state=root.querySelector('[data-account-status]').value,login=root.querySelector('[data-login-status]').value;[...root.querySelectorAll('.account-table>span')].forEach((cell,index)=>{const row=Math.floor(index/6),visible=accounts[row][4]===activeOrg&&(!query||accounts[row].join('').toLowerCase().includes(query))&&(state==='全部状态'||accounts[row][6]===state)&&(login==='全部登录状态'||accounts[row][3]===login);cell.hidden=!visible;});};root.querySelector('[data-account-search]').onclick=filter;root.querySelector('[data-account-reset]').onclick=()=>{root.querySelector('[data-account-query]').value='';root.querySelector('[data-account-status]').selectedIndex=0;root.querySelector('[data-login-status]').selectedIndex=0;filter();};root.querySelectorAll('[data-account-org]').forEach(button=>button.onclick=()=>{activeOrg=button.dataset.accountOrg;root.querySelectorAll('.account-org').forEach(item=>item.classList.toggle('active',item.contains(button)));filter();});bindActions(root);filter();
  }
  function renderRoles(){
    const root=document.getElementById('roleManagement');
    root.innerHTML=`<div class="sms-header"><div><h3>角色管理</h3><p>维护管理员角色及功能权限，系统角色不可删除。</p></div><button class="primary-button" data-admin-action="添加角色">＋ 添加角色</button></div><div class="admin-panel"><div class="admin-toolbar"><label><span>角色名称</span><input type="search" placeholder="请输入角色名称" data-role-query></label><label><span>角色类型</span><select data-role-type><option>全部类型</option><option>系统角色</option><option>自定义角色</option></select></label><button class="primary-button" data-role-search>查询</button></div><div class="role-table"><b>角色名称</b><b>角色描述</b><b>类型</b><b>账号数量</b><b>权限范围</b><b>操作</b>${roles.map(row=>`<span><strong>${row[0]}</strong></span><span>${row[1]}</span><span><em class="${row[2]==='系统角色'?'system':'custom'}">${row[2]}</em></span><span>${row[3]}</span><span>${row[4]}</span><span class="admin-actions"><button data-admin-action="查看权限">查看权限</button><button data-admin-action="编辑角色">编辑</button>${row[2]==='系统角色'?'<small>不可删除</small>':'<button data-admin-action="删除角色" class="danger">删除</button>'}</span>`).join('')}</div></div>`;
    const filter=()=>{const query=root.querySelector('[data-role-query]').value.trim().toLowerCase(),type=root.querySelector('[data-role-type]').value;[...root.querySelectorAll('.role-table>span')].forEach((cell,index)=>{const row=Math.floor(index/6),visible=(!query||roles[row][0].toLowerCase().includes(query))&&(type==='全部类型'||roles[row][2]===type);cell.hidden=!visible;});};root.querySelector('[data-role-search]').onclick=filter;bindActions(root);
  }
  renderOrganizations();renderAccounts();renderRoles();
})();
