/* 渠道配置原型：演示数据，不连接实际回传服务。 */
(() => {
  const categories=[['MOREN','默认分类','系统分类','通用默认渠道'],['bdpz','百度品专','系统分类','百度品牌专区'],['360pz','360品专','系统分类','360品牌专区'],['360sem','360SEM','系统分类','支持广告回传'],['sogousem','搜狗SEM','系统分类','支持广告回传'],['Wangyi','网易','系统分类','网易媒体渠道'],['ai','AI营销','自定义分类','AI助手及智能体渠道'],['bing','Bing SEM','自定义分类','Bing搜索投放渠道']];
  const channels=[['AI营销','aizhushou','官网AI助手','站内AI咨询入口','启用'],['AI营销','qiyeweixin','企业微信Agent','企业微信智能体','启用'],['AI营销','fuwuhao','服务号Agent','微信服务号智能体','启用'],['百度品专','baidupz01','百度品牌专区','百度品牌广告','启用'],['360SEM','360sem01','360搜索推广','支持oCPC回传','启用'],['搜狗SEM','sogou01','搜狗搜索推广','支持转化回传','停用'],['Bing SEM','bing02','Bing02','海外搜索推广','启用'],['抖音','douyinpz','抖音品专','短视频品牌专区','启用']];
  const toast=message=>{const node=document.getElementById('mkNavNotice');node.textContent=message;node.hidden=false;setTimeout(()=>node.hidden=true,2400);};
  function renderChannels(){
    const root=document.getElementById('channels');
    root.innerHTML=`<div class="sms-header"><div><h3>渠道管理</h3><p>维护营销渠道名称、编码、分类及转化回传能力。</p></div><button class="primary-button" data-channel-create>＋ 新建渠道</button></div><div class="channel-panel"><div class="channel-toolbar"><label><span>渠道名称</span><input type="search" placeholder="请输入渠道名称" data-channel-query></label><label><span>渠道分类</span><select data-channel-category><option>全部分类</option>${[...new Set(channels.map(row=>row[0]))].map(value=>`<option>${value}</option>`).join('')}</select></label><button class="primary-button" data-channel-search>查询</button></div><div class="channel-table"><b>渠道分类</b><b>渠道编码</b><b>渠道名称</b><b>描述</b><b>回传能力</b><b>操作</b>${channels.map(row=>`<span>${row[0]}</span><span><code>${row[1]}</code></span><span><strong>${row[2]}</strong></span><span>${row[3]}</span><span>${row[3].includes('回传')?'已配置':'—'}</span><span><button>编辑</button><button class="danger">删除</button></span>`).join('')}</div></div>`;
    const filter=()=>{const query=root.querySelector('[data-channel-query]').value.trim().toLowerCase(),category=root.querySelector('[data-channel-category]').value;[...root.querySelectorAll('.channel-table>span')].forEach((cell,index)=>{const row=Math.floor(index/6),visible=(!query||channels[row][2].toLowerCase().includes(query))&&(category==='全部分类'||channels[row][0]===category);cell.hidden=!visible;});};
    root.querySelector('[data-channel-search]').onclick=filter;root.querySelector('[data-channel-create]').onclick=()=>toast('新建渠道：本原型仅展示入口。');root.querySelectorAll('.channel-table button').forEach(button=>button.onclick=()=>toast(`${button.textContent}渠道：交互入口已保留。`));
  }
  function renderCategories(){
    const root=document.getElementById('channelCategories');let kind='系统分类';
    const paint=()=>{const rows=categories.filter(row=>row[2]===kind);root.querySelector('.category-table').innerHTML=`<b>分类编码</b><b>渠道分类</b><b>描述</b><b>包含渠道</b><b>操作</b>${rows.map(row=>`<span><code>${row[0]}</code></span><span><strong>${row[1]}</strong></span><span>${row[3]}</span><span>${channels.filter(channel=>channel[0]===row[1]).length}</span><span>${kind==='系统分类'?'<small>系统内置，不可编辑</small>':'<button>编辑</button><button class="danger">删除</button>'}</span>`).join('')}`;root.querySelectorAll('.category-table button').forEach(button=>button.onclick=()=>toast(`${button.textContent}分类：交互入口已保留。`));};
    root.innerHTML=`<div class="sms-header"><div><h3>渠道分类</h3><p>区分系统内置与业务自定义分类，统一渠道归类口径。</p></div><button class="primary-button" data-category-create>＋ 新建渠道分类</button></div><div class="channel-panel"><nav class="email-tabs" aria-label="渠道分类类型"><button class="active" data-category-kind="系统分类">系统渠道类型</button><button data-category-kind="自定义分类">自定义渠道类型</button></nav><div class="category-note"><b>系统渠道类型</b><span>由平台维护，用于标准渠道识别和数据回传，不支持编辑或删除。</span></div><div class="category-table"></div></div>`;
    root.querySelectorAll('[data-category-kind]').forEach(button=>button.onclick=()=>{kind=button.dataset.categoryKind;root.querySelectorAll('[data-category-kind]').forEach(item=>item.classList.toggle('active',item===button));root.querySelector('.category-note').innerHTML=kind==='系统分类'?'<b>系统渠道类型</b><span>由平台维护，用于标准渠道识别和数据回传，不支持编辑或删除。</span>':'<b>自定义渠道类型</b><span>由管理员维护，适合企业自有渠道和临时推广场景。</span>';paint();});root.querySelector('[data-category-create]').onclick=()=>toast('新建渠道分类：本原型仅展示入口。');paint();
  }
  renderChannels();renderCategories();
})();
